// GENERATED by scripts/build-web.js from src/windows.js, src/rates.js and
// src/ura-rates.js. Do not edit: change the source modules and rebuild.
window.CarparkRates = (function () {
  var windows = (function () {
    var module = { exports: {} };
    // Parses HDB's prose parking windows into something a computer can answer
    // "is it free right now?" with.
    //
    // The dataset writes these as English: "SUN & PH FR 7AM-10.30PM", "WHOLE DAY",
    // "NO". Times are minutes from midnight so comparisons are plain integers.
    //
    // DESIGN RULE: wording we do not recognise returns NO windows, i.e. "not free".
    // Guessing in the other direction tells someone parking is free when it is not,
    // and they get a fine. Being wrong in the safe direction costs them nothing.

    const DAY_NAMES = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"];

    // "7AM" -> 420, "10.30PM" -> 1350, "12AM" -> 0, "12PM" -> 720.
    // 12AM/12PM is the classic off-by-twelve bug: 12 means 0 in the morning and
    // stays 12 in the afternoon, unlike every other hour.
    function parseTime(raw) {
      const m = String(raw).trim().match(/^(\d{1,2})(?:[.:](\d{2}))?\s*(AM|PM)$/i);
      if (!m) return null;
      let h = parseInt(m[1], 10);
      const mins = m[2] ? parseInt(m[2], 10) : 0;
      const pm = m[3].toUpperCase() === "PM";
      if (h < 1 || h > 12 || mins > 59) return null;
      if (h === 12) h = 0;
      if (pm) h += 12;
      return h * 60 + mins;
    }

    function parseWindow(raw) {
      const s = String(raw || "").trim().toUpperCase();
      if (!s || s === "NO") return [];
      if (s === "WHOLE DAY") return [{ days: ["ALL"], from: 0, to: 1440 }];

      // Optional day prefix, then a time range: "SUN & PH FR 7AM-10.30PM".
      // "FR" is HDB's abbreviation for FROM, not Friday.
      const m = s.match(/^(?:(.+?)\s+FR\s+)?(\d{1,2}(?:[.:]\d{2})?\s*[AP]M)\s*-\s*(\d{1,2}(?:[.:]\d{2})?\s*[AP]M)$/);
      if (!m) return [];

      const from = parseTime(m[2]);
      const to = parseTime(m[3]);
      if (from === null || to === null || to <= from) return [];

      let days = ["ALL"];
      if (m[1]) {
        const tokens = m[1].split(/\s*&\s*|\s*,\s*/).map((t) => t.trim());
        const known = tokens.map((t) => (t === "PH" || DAY_NAMES.includes(t) ? t : null));
        // One unrecognised day token invalidates the whole window rather than
        // silently dropping it - a partial reading is worse than none.
        if (known.some((k) => k === null)) return [];
        days = known;
      }
      return [{ days, from, to }];
    }

    // The predicate itself, in the terms the windows are stored in: a day name and
    // minutes past midnight. src/rates.js walks a stay a minute at a time and needs
    // to ask this thousands of times without building a Date for each one, so the
    // comparison lives here once rather than being reimplemented there.
    function matchesWindow(windows, dayName, minutes, isPublicHoliday) {
      if (!Array.isArray(windows) || !windows.length) return false;
      return windows.some((w) => {
        const dayMatches =
          w.days.includes("ALL") ||
          w.days.includes(dayName) ||
          (isPublicHoliday && w.days.includes("PH"));
        return dayMatches && minutes >= w.from && minutes < w.to;
      });
    }

    // `isPublicHoliday` is passed in rather than looked up here: a public holiday
    // falling on a weekday is exactly the case a day-of-week check gets wrong, and
    // the holiday calendar is a separate concern with its own update schedule.
    function isFreeAt(windows, when, isPublicHoliday) {
      // Singapore is UTC+8 with no daylight saving, so local time is deterministic.
      const sg = new Date(when.getTime() + 8 * 3600 * 1000);
      return matchesWindow(
        windows,
        DAY_NAMES[sg.getUTCDay()],
        sg.getUTCHours() * 60 + sg.getUTCMinutes(),
        isPublicHoliday
      );
    }

    module.exports = { parseWindow, isFreeAt, matchesWindow, parseTime, DAY_NAMES };

    return module.exports;
  })();

  var rates = (function () {
    var module = { exports: {} };
    // What a stay actually costs, from HDB's published rate schedule.
    //
    // WHY THIS IS HAND-ENTERED: there is no parking-rate dataset. data.gov.sg
    // publishes carpark locations and live availability but not a single price;
    // every dataset was checked. HDB publishes the schedule as a web page only.
    // So the numbers below are transcribed from that page, pinned with the date
    // they were read, and scripts/check-rates.js re-reads the page and fails
    // loudly if any of them moves. That is the honest version of hard-coding:
    // say where it came from, and notice when it goes stale.
    //
    // Source: https://www.hdb.gov.sg/parking/other-parking-matters/shortterm-parking/shortterm-parking-charges
    //         https://www.hdb.gov.sg/parking/other-parking-matters/shortterm-parking/electronic-parking
    //
    // DESIGN RULE, inherited from src/windows.js: where the schedule does not say,
    // do not invent. A stay we cannot price returns null and a reason, never $0.
    // A free-looking price that turns out to be wrong is the one failure that
    // costs the user real money.

    const { matchesWindow, DAY_NAMES } = windows;

    const WEEKDAYS = ["MON", "TUE", "WED", "THU", "FRI"];
    const WEEKENDS = ["SAT", "SUN"];
    const MON_SAT = ["MON", "TUE", "WED", "THU", "FRI", "SAT"];

    const RATES = {
      source: "https://www.hdb.gov.sg/parking/other-parking-matters/shortterm-parking/shortterm-parking-charges",
      // What HDB's own page says it was last updated. Not when we read it.
      publishedOn: "2026-07-24",
      checkedOn: "2026-08-25",

      // Dollars per half hour, for motor cars.
      standard: 0.6,
      standardPeak: 0.8,
      central: 1.2,
      centralPeak: 1.4,

      // The Central Area premium applies only in this window; outside it a Central
      // Area carpark charges the ordinary rate.
      centralWindow: { days: MON_SAT, from: 7 * 60, to: 17 * 60 },

      // Night runs from 10.30pm to 7am the following morning.
      nightFrom: 22 * 60 + 30,
      nightTo: 7 * 60,

      caps: { night: 5, day: 12, dayCentral: 20 },

      // Electronic carparks only. "You will not be charged if you exit within 15
      // minutes of entry" - it is a threshold, not a discount off a longer stay.
      graceMinutes: 15,

      // The 16 carparks HDB lists as being in the Central Area.
      centralArea: [
        "ACB", "BBB", "BRB1", "CY", "DUXM", "HLM", "KAB", "KAM",
        "KAS", "PRM", "SLS", "SR1", "SR2", "TPM", "UCS", "WCB",
      ],

      // The 12 carparks with peak-hour surcharges, each with its own peak periods.
      // Caps do not apply at any of these.
      peakHour: {
        ACB: [{ days: WEEKDAYS, from: 10 * 60, to: 18 * 60 }, { days: WEEKENDS, from: 8 * 60, to: 19 * 60 }],
        CY: [{ days: WEEKDAYS, from: 10 * 60, to: 18 * 60 }, { days: WEEKENDS, from: 8 * 60, to: 19 * 60 }],
        SE21: [{ days: MON_SAT, from: 10 * 60, to: 22 * 60 }],
        SE22: [{ days: MON_SAT, from: 10 * 60, to: 22 * 60 }],
        SE24: [{ days: ["ALL"], from: 10 * 60, to: 22 * 60 }],
        MP14: [{ days: ["ALL"], from: 8 * 60, to: 20 * 60 }],
        MP15: [{ days: ["ALL"], from: 8 * 60, to: 20 * 60 }],
        MP16: [{ days: ["ALL"], from: 8 * 60, to: 20 * 60 }],
        HG9: [{ days: WEEKDAYS, from: 11 * 60, to: 20 * 60 }, { days: WEEKENDS, from: 9 * 60, to: 20 * 60 }],
        HG9T: [{ days: WEEKDAYS, from: 11 * 60, to: 20 * 60 }, { days: WEEKENDS, from: 9 * 60, to: 20 * 60 }],
        HG15: [{ days: WEEKDAYS, from: 11 * 60, to: 20 * 60 }, { days: WEEKENDS, from: 9 * 60, to: 20 * 60 }],
        HG16: [{ days: WEEKDAYS, from: 11 * 60, to: 20 * 60 }, { days: WEEKENDS, from: 9 * 60, to: 20 * 60 }],
      },
    };

    // "hdb:ACB" -> "ACB". Only HDB rates are known, so a carpark from a future
    // URA or LTA adapter falls through as neither Central nor peak, and its own
    // adapter will bring its own schedule.
    function carparkNumber(id) {
      const s = String(id || "");
      const i = s.indexOf(":");
      return (i === -1 ? s : s.slice(i + 1)).toUpperCase();
    }

    function isHdb(id) {
      return String(id || "").startsWith("hdb:");
    }

    function isCentral(id) {
      return isHdb(id) && RATES.centralArea.includes(carparkNumber(id));
    }

    function hasPeakCharges(id) {
      return isHdb(id) && Object.prototype.hasOwnProperty.call(RATES.peakHour, carparkNumber(id));
    }

    // Minutes since the Unix epoch in Singapore local time. Singapore is UTC+8
    // with no daylight saving, so this is exact and needs no timezone library.
    function sgMinutes(when) {
      return Math.floor((when.getTime() + 8 * 3600 * 1000) / 60000);
    }

    // 1 January 1970 was a Thursday, which is index 4 in DAY_NAMES.
    function dayNameOf(dayNumber) {
      return DAY_NAMES[(((dayNumber % 7) + 4) % 7 + 7) % 7];
    }

    function isoDateOf(dayNumber) {
      return new Date(dayNumber * 86400000).toISOString().slice(0, 10);
    }

    function isNightMinute(minuteOfDay) {
      return minuteOfDay >= RATES.nightFrom || minuteOfDay < RATES.nightTo;
    }

    // The posted rate at a moment, ignoring whether this particular carpark is
    // giving the parking away under the free-parking scheme.
    function rateHalfHourAt(id, when, isPublicHoliday) {
      const tm = sgMinutes(when);
      const day = Math.floor(tm / 1440);
      return rateAt(id, dayNameOf(day), tm - day * 1440, !!isPublicHoliday);
    }

    function rateAt(id, dayName, minuteOfDay, isPublicHoliday) {
      const peak = hasPeakCharges(id) &&
        matchesWindow(RATES.peakHour[carparkNumber(id)], dayName, minuteOfDay, isPublicHoliday);

      const centralPremium = isCentral(id) &&
        matchesWindow([RATES.centralWindow], dayName, minuteOfDay, isPublicHoliday);

      if (centralPremium) return peak ? RATES.centralPeak : RATES.central;
      return peak ? RATES.standardPeak : RATES.standard;
    }

    const cents = (n) => Math.round(n * 100) / 100;

    // carpark needs: id, parkingSystem, nightParking, shortTermParking, freeParking
    //   (shortTermParking / freeParking are parsed windows from src/windows.js)
    // start:   a Date, the moment the car enters
    // minutes: how long it stays
    // isHoliday: (isoDate) => boolean
    function feeFor(carpark, start, minutes, isHoliday) {
      const holiday = typeof isHoliday === "function" ? isHoliday : () => false;
      const total = Math.max(0, Math.round(minutes));
      const id = carpark.id;
      const coupon = /COUPON/i.test(carpark.parkingSystem || "");
      const nps = !!carpark.nightParking;
      const shortTerm = carpark.shortTermParking || [];
      const free = carpark.freeParking || [];
      const uncapped = hasPeakCharges(id);
      const dayCap = isCentral(id) ? RATES.caps.dayCentral : RATES.caps.day;

      const blank = {
        total: null, free: false, grace: false, capApplied: null,
        lines: [], couponTotal: null, minutes: total,
        method: coupon ? "coupon" : "electronic",
        central: isCentral(id), peak: uncapped,
      };

      if (!total) return { ...blank, total: 0, lines: [] };

      const startMin = sgMinutes(start);
      const isoCache = new Map();
      const isoFor = (day) => {
        if (!isoCache.has(day)) isoCache.set(day, isoDateOf(day));
        return isoCache.get(day);
      };

      // One pass over the stay. Every minute is classified, priced, and filed
      // under the parking day whose cap it counts against.
      const buckets = new Map(); // parkingDay -> { day, night }
      const runs = [];           // consecutive minutes at the same rate
      let anyChargeable = false;

      for (let m = 0; m < total; m++) {
        const tm = startMin + m;
        const day = Math.floor(tm / 1440);
        const mod = tm - day * 1440;
        const dayName = dayNameOf(day);
        const ph = holiday(isoFor(day));
        const night = isNightMinute(mod);

        // Can a non-season driver be here at all? Short-term hours cover the day;
        // the Night Parking Scheme covers 10.30pm-7am where the carpark has it.
        const parkable = matchesWindow(shortTerm, dayName, mod, ph) || (nps && night);
        if (!parkable) {
          const seasonOnly = !shortTerm.length && !nps;
          return { ...blank, unavailable: seasonOnly ? "season-only" : "outside-hours" };
        }

        const isFree = matchesWindow(free, dayName, mod, ph);
        const rate = isFree ? 0 : rateAt(id, dayName, mod, ph);
        if (rate > 0) anyChargeable = true;

        const last = runs[runs.length - 1];
        if (last && last.rate === rate) last.minutes++;
        else runs.push({ rate, minutes: 1, startMinute: tm });

        // A parking day runs 7am to 7am, so the small hours belong to the night
        // before - which is what makes "capped at $5 per night" mean one night.
        const parkingDay = mod >= RATES.nightTo ? day : day - 1;
        if (!buckets.has(parkingDay)) buckets.set(parkingDay, { day: 0, night: 0 });
        const b = buckets.get(parkingDay);
        b[night ? "night" : "day"] += rate / 30;
      }

      // Grace comes after the parkability check: a carpark you may not enter is
      // not free to enter for 15 minutes.
      if (!coupon && total <= RATES.graceMinutes) {
        return { ...blank, total: 0, grace: true, free: !anyChargeable, unavailable: null };
      }

      let metered = 0;
      let charged = 0;
      let capApplied = null;
      for (const b of buckets.values()) {
        metered += b.day + b.night;
        if (uncapped) { charged += b.day + b.night; continue; }

        let night = b.night;
        if (nps && night > RATES.caps.night) { night = RATES.caps.night; capApplied = "night"; }

        if (nps) {
          const whole = b.day + night;
          if (whole > dayCap) { charged += dayCap; capApplied = "day"; }
          else charged += whole;
        } else {
          if (b.day > dayCap) { charged += dayCap + night; capApplied = "day"; }
          else charged += b.day + night;
        }
      }

      const lines = runs.map((r) => ({
        rate: r.rate,
        minutes: r.minutes,
        from: new Date((r.startMinute - 8 * 60) * 60000),
        to: new Date((r.startMinute + r.minutes - 8 * 60) * 60000),
        amount: cents((r.rate / 30) * r.minutes),
        label: r.rate === 0 ? "Free parking" : "$" + r.rate.toFixed(2) + " per half hour",
      }));

      // Make the breakdown reconcile: if a cap bit, show it as the discount it is.
      const discount = cents(charged) - lines.reduce((a, l) => a + l.amount, 0);
      if (capApplied && Math.abs(discount) >= 0.01) {
        lines.push({
          rate: null, minutes: 0, from: null, to: null,
          amount: cents(discount),
          label: capApplied === "night"
            ? "Night cap ($" + RATES.caps.night + ")"
            : "Daily cap ($" + dayCap + ")",
        });
      }

      return {
        ...blank,
        total: cents(charged),
        metered: cents(metered),
        free: !anyChargeable,
        capApplied,
        lines,
        unavailable: null,
        couponTotal: coupon ? couponPrice(id, startMin, total, shortTerm, free, holiday, isoFor) : null,
      };
    }

    // Paper coupons come in half-hour denominations, so an occupied half hour is a
    // whole coupon however little of it you use. Parking.sg prices the same stay by
    // the minute, which is what `total` reports - both are shown rather than one
    // quietly chosen for the driver.
    function couponPrice(id, startMin, minutes, shortTerm, free, holiday, isoFor) {
      let sum = 0;
      for (let block = 0; block * 30 < minutes; block++) {
        const tm = startMin + block * 30;
        const day = Math.floor(tm / 1440);
        const mod = tm - day * 1440;
        const dayName = dayNameOf(day);
        const ph = holiday(isoFor(day));
        if (matchesWindow(free, dayName, mod, ph)) continue;
        sum += rateAt(id, dayName, mod, ph);
      }
      return cents(sum);
    }

    module.exports = {
      RATES, feeFor, rateHalfHourAt, isCentral, hasPeakCharges, carparkNumber,
    };

    return module.exports;
  })();

  var uraRates = (function () {
    var module = { exports: {} };
    // What a stay costs at a URA carpark, from URA's own published rate table.
    //
    // WHY THIS IS NOT src/rates.js: HDB's schedule is one national table that had
    // to be transcribed off a web page. URA's arrives as data - every carpark
    // carries its own windows and prices in Car_Park_Details - so this engine is
    // driven entirely by the carpark record and hard-codes no price at all. That
    // is a strictly better position, and the reason the spec said to give each
    // adapter its own feeFor rather than grow one global table.
    //
    // It returns the SAME shape as rates.js#feeFor so the page can price a mixed
    // list of HDB and URA carparks without knowing which is which.
    //
    // DESIGN RULE, inherited from the rest of this project: where the data does
    // not say, do not invent. A stay we cannot price returns null and a reason,
    // never $0.

    // URA writes times as "07.00 AM" / "10.30 PM", and a window whose end is at or
    // before its start wraps past midnight ("10.30 PM" - "07.00 AM").
    function parseTime(s) {
      const m = /^(\d{1,2})\.(\d{2})\s*(AM|PM)$/i.exec(String(s || "").trim());
      if (!m) return null;
      const hh = Number(m[1]);
      const mm = Number(m[2]);
      if (hh > 12 || mm > 59) return null;
      const h = (hh % 12) + (/PM/i.test(m[3]) ? 12 : 0);
      return h * 60 + mm;
    }

    const money = (s) => {
      if (s === undefined || s === null) return null;
      const n = Number(String(s).replace(/[$,\s]/g, ""));
      return isFinite(n) ? n : null;
    };

    const unitMinutes = (s) => {
      if (s === undefined || s === null) return null;
      const n = Number(String(s).replace(/\s*mins?\s*$/i, ""));
      return isFinite(n) ? n : null;
    };

    const DAY_KEYS = ["wd", "sat", "sun"];

    // Which of URA's three rate columns applies. Public holidays are priced as
    // Sunday because that is the column URA labels "sunPH".
    function dayKey(dayOfWeek, isPublicHoliday) {
      if (isPublicHoliday || dayOfWeek === 0) return "sun";
      return dayOfWeek === 6 ? "sat" : "wd";
    }

    const COLUMNS = {
      wd: ["weekdayRate", "weekdayMin"],
      sat: ["satdayRate", "satdayMin"],
      sun: ["sunPHRate", "sunPHMin"],
    };

    // Turn the rows Car_Park_Details gives for ONE carpark into a table this
    // engine can walk. Rows are grouped by their time window; a window may carry
    // two rows, and the second is not a second rate:
    //
    //   ANGULLIA PARK OFF ST, 10.30 PM - 07.00 AM
    //     $0.70 / 30 mins     <- what it accrues at
    //     $5.60 / 510 mins    <- 510 min IS the window, so this is the whole night
    //
    // Charging 17 half hours would bill $11.90 for a night URA sells at $5.60.
    // The rule below - a row whose charging unit equals the window length is a
    // flat price for that window - was checked against every such pair in the
    // live data: 146 of 146, and in all 146 the flat price is the cheaper one.
    function parseRateTable(rows) {
      const groups = new Map();
      for (const r of rows || []) {
        const from = parseTime(r.startTime);
        const to = parseTime(r.endTime);
        if (from === null || to === null) continue;
        const key = from + "-" + to;
        if (!groups.has(key)) groups.set(key, { from, to, rows: [] });
        groups.get(key).rows.push(r);
      }

      const windows = [];
      for (const g of groups.values()) {
        const span = g.to > g.from ? g.to - g.from : g.to + 1440 - g.from;
        const w = { from: g.from, to: g.to, span, wd: null, sat: null, sun: null };

        for (const key of DAY_KEYS) {
          const [rateField, minField] = COLUMNS[key];
          let unitRate = null;
          let flat = null;
          for (const r of g.rows) {
            const price = money(r[rateField]);
            const unit = unitMinutes(r[minField]);
            // Absent, not zero. URA writes an explicit "$0.00 / 0 mins" where
            // parking really is free, so a row with no rate fields at all means
            // something else - and both candidate meanings (free, or no parking
            // allowed) cannot be told apart from here. Neither is assumed.
            if (price === null || unit === null) continue;
            if (unit === 0 || price === 0) { unitRate = { rate: 0, unit: 30 }; continue; }
            if (unit === span) flat = price;
            else unitRate = { rate: price, unit };
          }
          if (unitRate) w[key] = { rate: unitRate.rate, unit: unitRate.unit, flat };
        }
        windows.push(w);
      }

      windows.sort((a, b) => a.from - b.from);
      return windows;
    }

    function covers(w, minuteOfDay) {
      if (w.to > w.from) return minuteOfDay >= w.from && minuteOfDay < w.to;
      return minuteOfDay >= w.from || minuteOfDay < w.to;   // wraps past midnight
    }

    function windowAt(windows, minuteOfDay) {
      for (let i = 0; i < windows.length; i++) if (covers(windows[i], minuteOfDay)) return i;
      return -1;
    }

    // Minutes since the Unix epoch in Singapore local time. Singapore is UTC+8
    // with no daylight saving, so this is exact and needs no timezone library.
    function sgMinutes(when) {
      return Math.floor((when.getTime() + 8 * 3600 * 1000) / 60000);
    }

    // 1 January 1970 was a Thursday, so day 0 is weekday 4.
    const dayOfWeekOf = (dayNumber) => (((dayNumber + 4) % 7) + 7) % 7;
    const isoDateOf = (dayNumber) => new Date(dayNumber * 86400000).toISOString().slice(0, 10);
    const cents = (n) => Math.round(n * 100) / 100;

    // carpark needs: id, parkingSystem ("C" coupon / "B" electronic), rates
    //   (the windows produced by parseRateTable)
    // start:   a Date, the moment the car enters
    // minutes: how long it stays
    // isHoliday: (isoDate) => boolean
    function feeFor(carpark, start, minutes, isHoliday) {
      const holiday = typeof isHoliday === "function" ? isHoliday : () => false;
      const total = Math.max(0, Math.round(minutes));
      const windows = (carpark && carpark.rates) || [];
      // The adapter normalises URA's "C"/"B" into the same wording HDB uses, so
      // both rate engines test one vocabulary.
      const coupon = /COUPON/i.test(String((carpark && carpark.parkingSystem) || ""));

      const blank = {
        total: null, free: false, grace: false, capApplied: null,
        lines: [], couponTotal: null, minutes: total, metered: null,
        method: coupon ? "coupon" : "electronic",
        central: false, peak: false, unavailable: null,
      };

      if (!windows.length) return { ...blank, unavailable: "no-rates" };
      if (!total) return { ...blank, total: 0 };

      const startMin = sgMinutes(start);
      const isoCache = new Map();
      const isoFor = (day) => {
        if (!isoCache.has(day)) isoCache.set(day, isoDateOf(day));
        return isoCache.get(day);
      };

      // One pass over the stay, kept at two levels.
      //
      // An OCCURRENCE is one contiguous stay inside a single window, and it is what
      // the flat price caps: staying a whole night buys the night, staying an hour
      // of it does not. Every one of the 152 flat rows in the live data covers a
      // window that crosses midnight, so grouping by calendar day instead would
      // break the cap on every stay beginning on a Saturday or a holiday eve and
      // silently overcharge for it.
      //
      // A RUN is a stretch within an occurrence that shares one rate. Runs exist
      // because the rate column changes at midnight (Saturday's rate is not
      // Sunday's), so they keep the accrual honest and give the breakdown its
      // line items - but they never carry the cap.
      const occurrences = [];
      let anyChargeable = false;

      for (let m = 0; m < total; m++) {
        const tm = startMin + m;
        const day = Math.floor(tm / 1440);
        const mod = tm - day * 1440;
        const key = dayKey(dayOfWeekOf(day), holiday(isoFor(day)));

        const wi = windowAt(windows, mod);
        // The windows tile all 1,440 minutes for every carpark in the live data,
        // so a miss means this carpark's table is malformed rather than that the
        // driver has found a gap. Either way it cannot be priced.
        if (wi === -1) return { ...blank, unavailable: "rate-not-published" };

        const spec = windows[wi][key];
        // No rate published for this window on this kind of day. In the live data
        // this is always an on-street carpark overnight or in the morning peak -
        // it may mean free, it may mean no parking at all, and guessing "free" is
        // the guess that earns a fine.
        if (!spec) return { ...blank, unavailable: "rate-not-published" };
        if (spec.rate > 0) anyChargeable = true;

        let occ = occurrences[occurrences.length - 1];
        if (!occ || occ.wi !== wi) {
          // The flat price is read at the moment the car arrives, the way a driver
          // would understand buying the night. The live data shows no flat that
          // differs between weekday, Saturday and Sunday, so this choice is not
          // currently load-bearing - but it has to be made explicitly.
          occ = { wi, flat: spec.flat, runs: [] };
          occurrences.push(occ);
        }
        const last = occ.runs[occ.runs.length - 1];
        if (last && last.spec === spec) last.minutes++;
        else occ.runs.push({ spec, minutes: 1, startMinute: tm });
      }

      let metered = 0;
      let charged = 0;
      let capApplied = null;
      for (const occ of occurrences) {
        occ.accrued = occ.runs.reduce((a, r) => a + (r.spec.rate / r.spec.unit) * r.minutes, 0);
        metered += occ.accrued;
        if (occ.flat !== null && occ.flat !== undefined && occ.accrued > occ.flat) {
          occ.charged = occ.flat;
          capApplied = "window";
        } else {
          occ.charged = occ.accrued;
        }
        charged += occ.charged;
      }

      // Line items are the runs at what they accrued, and a capped occurrence adds
      // the cap as the discount it is - so the breakdown adds up to the total
      // rather than asking the reader to take the total on trust.
      const lines = [];
      for (const occ of occurrences) {
        for (const r of occ.runs) {
          lines.push({
            rate: r.spec.rate,
            minutes: r.minutes,
            from: new Date((r.startMinute - 8 * 60) * 60000),
            to: new Date((r.startMinute + r.minutes - 8 * 60) * 60000),
            amount: cents((r.spec.rate / r.spec.unit) * r.minutes),
            label: r.spec.rate === 0
              ? "Free parking"
              : "$" + r.spec.rate.toFixed(2) + " per " + r.spec.unit + " min",
          });
        }
        if (occ.charged !== occ.accrued) {
          lines.push({
            rate: null, minutes: 0, from: null, to: null,
            amount: cents(occ.charged - occ.accrued),
            label: capLabel(windows[occ.wi], occ.flat),
          });
        }
      }

      return {
        ...blank,
        total: cents(charged),
        metered: cents(metered),
        free: !anyChargeable,
        capApplied,
        lines,
        couponTotal: coupon ? couponPrice(occurrences) : null,
      };
    }

    const clock = (m) => {
      const h = Math.floor(m / 60) % 24;
      const mm = String(m % 60).padStart(2, "0");
      const ampm = h < 12 ? "am" : "pm";
      return ((h % 12) || 12) + "." + mm + ampm;
    };

    function capLabel(w, flat) {
      const whole = w.to <= w.from ? "night" : "period";
      return "Whole-" + whole + " rate, " + clock(w.from) + "-" + clock(w.to) +
        " ($" + flat.toFixed(2) + ")";
    }

    // A paper coupon buys a whole charging block however little of it you use, so
    // an occupied block is a whole coupon. Shown alongside the by-the-minute figure
    // rather than one being quietly chosen for the driver. The flat price caps a
    // coupon stay too - you would simply not display more coupons than that.
    function couponPrice(occurrences) {
      let sum = 0;
      for (const occ of occurrences) {
        let blocks = 0;
        for (const r of occ.runs) {
          if (!r.spec.rate) continue;
          blocks += Math.ceil(r.minutes / r.spec.unit) * r.spec.rate;
        }
        sum += occ.flat !== null && occ.flat !== undefined ? Math.min(blocks, occ.flat) : blocks;
      }
      return cents(sum);
    }

    module.exports = { parseRateTable, feeFor, parseTime, dayKey, windowAt, covers };

    return module.exports;
  })();

  return { rates: rates, windows: windows, ura: uraRates };
})();
